// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/PantsProtocol.proto

package org.kndl.pants;

public final class PantsProtocol {
  private PantsProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PantsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.kndl.pants.Pants)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .org.kndl.pants.Pants.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .org.kndl.pants.Pants.Type type = 1;</code>
     */
    org.kndl.pants.PantsProtocol.Pants.Type getType();

    /**
     * <code>optional string username = 2;</code>
     */
    boolean hasUsername();
    /**
     * <code>optional string username = 2;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 2;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>optional string password = 3;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 3;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 3;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional bool loggedIn = 4;</code>
     */
    boolean hasLoggedIn();
    /**
     * <code>optional bool loggedIn = 4;</code>
     */
    boolean getLoggedIn();

    /**
     * <code>optional int64 userId = 5;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional int64 userId = 5;</code>
     */
    long getUserId();

    /**
     * <code>optional int32 versionMajor = 6;</code>
     */
    boolean hasVersionMajor();
    /**
     * <code>optional int32 versionMajor = 6;</code>
     */
    int getVersionMajor();

    /**
     * <code>optional int32 versionMinor = 7;</code>
     */
    boolean hasVersionMinor();
    /**
     * <code>optional int32 versionMinor = 7;</code>
     */
    int getVersionMinor();

    /**
     * <code>optional int32 versionPatch = 8;</code>
     */
    boolean hasVersionPatch();
    /**
     * <code>optional int32 versionPatch = 8;</code>
     */
    int getVersionPatch();

    /**
     * <code>optional int64 channelId = 9;</code>
     */
    boolean hasChannelId();
    /**
     * <code>optional int64 channelId = 9;</code>
     */
    long getChannelId();

    /**
     * <code>optional string channelName = 10;</code>
     */
    boolean hasChannelName();
    /**
     * <code>optional string channelName = 10;</code>
     */
    java.lang.String getChannelName();
    /**
     * <code>optional string channelName = 10;</code>
     */
    com.google.protobuf.ByteString
        getChannelNameBytes();

    /**
     * <code>optional string message = 11;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 11;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 11;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>optional int64 timestamp = 12;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 12;</code>
     */
    long getTimestamp();

    /**
     * <code>optional bytes data = 254;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 254;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code org.kndl.pants.Pants}
   */
  public static final class Pants extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.kndl.pants.Pants)
      PantsOrBuilder {
    // Use Pants.newBuilder() to construct.
    private Pants(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Pants(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Pants defaultInstance;
    public static Pants getDefaultInstance() {
      return defaultInstance;
    }

    public Pants getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Pants(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.kndl.pants.PantsProtocol.Pants.Type value = org.kndl.pants.PantsProtocol.Pants.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              username_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              password_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              loggedIn_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              userId_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              versionMajor_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              versionMinor_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              versionPatch_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              channelId_ = input.readInt64();
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              channelName_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              message_ = bs;
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              timestamp_ = input.readInt64();
              break;
            }
            case 2034: {
              bitField0_ |= 0x00001000;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.kndl.pants.PantsProtocol.internal_static_org_kndl_pants_Pants_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.kndl.pants.PantsProtocol.internal_static_org_kndl_pants_Pants_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.kndl.pants.PantsProtocol.Pants.class, org.kndl.pants.PantsProtocol.Pants.Builder.class);
    }

    public static com.google.protobuf.Parser<Pants> PARSER =
        new com.google.protobuf.AbstractParser<Pants>() {
      public Pants parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pants(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Pants> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.kndl.pants.Pants.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LOGIN_REQUEST = 0;</code>
       */
      LOGIN_REQUEST(0, 0),
      /**
       * <code>LOGIN_RESPONSE = 1;</code>
       */
      LOGIN_RESPONSE(1, 1),
      /**
       * <code>VERSION = 2;</code>
       */
      VERSION(2, 2),
      /**
       * <code>JOIN_REQUEST = 3;</code>
       */
      JOIN_REQUEST(3, 3),
      /**
       * <code>JOIN_RESPONSE = 4;</code>
       */
      JOIN_RESPONSE(4, 4),
      /**
       * <code>MSG = 5;</code>
       */
      MSG(5, 5),
      /**
       * <code>PRIVMSG = 6;</code>
       */
      PRIVMSG(6, 6),
      /**
       * <code>PING = 7;</code>
       */
      PING(7, 7),
      /**
       * <code>PONG = 8;</code>
       */
      PONG(8, 8),
      /**
       * <code>CONTROL = 254;</code>
       */
      CONTROL(9, 254),
      ;

      /**
       * <code>LOGIN_REQUEST = 0;</code>
       */
      public static final int LOGIN_REQUEST_VALUE = 0;
      /**
       * <code>LOGIN_RESPONSE = 1;</code>
       */
      public static final int LOGIN_RESPONSE_VALUE = 1;
      /**
       * <code>VERSION = 2;</code>
       */
      public static final int VERSION_VALUE = 2;
      /**
       * <code>JOIN_REQUEST = 3;</code>
       */
      public static final int JOIN_REQUEST_VALUE = 3;
      /**
       * <code>JOIN_RESPONSE = 4;</code>
       */
      public static final int JOIN_RESPONSE_VALUE = 4;
      /**
       * <code>MSG = 5;</code>
       */
      public static final int MSG_VALUE = 5;
      /**
       * <code>PRIVMSG = 6;</code>
       */
      public static final int PRIVMSG_VALUE = 6;
      /**
       * <code>PING = 7;</code>
       */
      public static final int PING_VALUE = 7;
      /**
       * <code>PONG = 8;</code>
       */
      public static final int PONG_VALUE = 8;
      /**
       * <code>CONTROL = 254;</code>
       */
      public static final int CONTROL_VALUE = 254;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return LOGIN_REQUEST;
          case 1: return LOGIN_RESPONSE;
          case 2: return VERSION;
          case 3: return JOIN_REQUEST;
          case 4: return JOIN_RESPONSE;
          case 5: return MSG;
          case 6: return PRIVMSG;
          case 7: return PING;
          case 8: return PONG;
          case 254: return CONTROL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.kndl.pants.PantsProtocol.Pants.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.kndl.pants.Pants.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private org.kndl.pants.PantsProtocol.Pants.Type type_;
    /**
     * <code>required .org.kndl.pants.Pants.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .org.kndl.pants.Pants.Type type = 1;</code>
     */
    public org.kndl.pants.PantsProtocol.Pants.Type getType() {
      return type_;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private java.lang.Object username_;
    /**
     * <code>optional string username = 2;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private java.lang.Object password_;
    /**
     * <code>optional string password = 3;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGGEDIN_FIELD_NUMBER = 4;
    private boolean loggedIn_;
    /**
     * <code>optional bool loggedIn = 4;</code>
     */
    public boolean hasLoggedIn() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool loggedIn = 4;</code>
     */
    public boolean getLoggedIn() {
      return loggedIn_;
    }

    public static final int USERID_FIELD_NUMBER = 5;
    private long userId_;
    /**
     * <code>optional int64 userId = 5;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 userId = 5;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int VERSIONMAJOR_FIELD_NUMBER = 6;
    private int versionMajor_;
    /**
     * <code>optional int32 versionMajor = 6;</code>
     */
    public boolean hasVersionMajor() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 versionMajor = 6;</code>
     */
    public int getVersionMajor() {
      return versionMajor_;
    }

    public static final int VERSIONMINOR_FIELD_NUMBER = 7;
    private int versionMinor_;
    /**
     * <code>optional int32 versionMinor = 7;</code>
     */
    public boolean hasVersionMinor() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 versionMinor = 7;</code>
     */
    public int getVersionMinor() {
      return versionMinor_;
    }

    public static final int VERSIONPATCH_FIELD_NUMBER = 8;
    private int versionPatch_;
    /**
     * <code>optional int32 versionPatch = 8;</code>
     */
    public boolean hasVersionPatch() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 versionPatch = 8;</code>
     */
    public int getVersionPatch() {
      return versionPatch_;
    }

    public static final int CHANNELID_FIELD_NUMBER = 9;
    private long channelId_;
    /**
     * <code>optional int64 channelId = 9;</code>
     */
    public boolean hasChannelId() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int64 channelId = 9;</code>
     */
    public long getChannelId() {
      return channelId_;
    }

    public static final int CHANNELNAME_FIELD_NUMBER = 10;
    private java.lang.Object channelName_;
    /**
     * <code>optional string channelName = 10;</code>
     */
    public boolean hasChannelName() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string channelName = 10;</code>
     */
    public java.lang.String getChannelName() {
      java.lang.Object ref = channelName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          channelName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string channelName = 10;</code>
     */
    public com.google.protobuf.ByteString
        getChannelNameBytes() {
      java.lang.Object ref = channelName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 11;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 11;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string message = 11;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 11;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 12;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 12;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int64 timestamp = 12;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int DATA_FIELD_NUMBER = 254;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 254;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional bytes data = 254;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      type_ = org.kndl.pants.PantsProtocol.Pants.Type.LOGIN_REQUEST;
      username_ = "";
      password_ = "";
      loggedIn_ = false;
      userId_ = 0L;
      versionMajor_ = 0;
      versionMinor_ = 0;
      versionPatch_ = 0;
      channelId_ = 0L;
      channelName_ = "";
      message_ = "";
      timestamp_ = 0L;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, loggedIn_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, userId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, versionMajor_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, versionMinor_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, versionPatch_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, channelId_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getChannelNameBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getMessageBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt64(12, timestamp_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(254, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, loggedIn_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, userId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, versionMajor_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, versionMinor_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, versionPatch_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, channelId_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getChannelNameBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getMessageBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, timestamp_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(254, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.kndl.pants.PantsProtocol.Pants parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kndl.pants.PantsProtocol.Pants parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kndl.pants.PantsProtocol.Pants parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kndl.pants.PantsProtocol.Pants parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kndl.pants.PantsProtocol.Pants parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.kndl.pants.PantsProtocol.Pants parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.kndl.pants.PantsProtocol.Pants parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.kndl.pants.PantsProtocol.Pants parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.kndl.pants.PantsProtocol.Pants parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.kndl.pants.PantsProtocol.Pants parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.kndl.pants.PantsProtocol.Pants prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.kndl.pants.Pants}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.kndl.pants.Pants)
        org.kndl.pants.PantsProtocol.PantsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kndl.pants.PantsProtocol.internal_static_org_kndl_pants_Pants_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kndl.pants.PantsProtocol.internal_static_org_kndl_pants_Pants_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.kndl.pants.PantsProtocol.Pants.class, org.kndl.pants.PantsProtocol.Pants.Builder.class);
      }

      // Construct using org.kndl.pants.PantsProtocol.Pants.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = org.kndl.pants.PantsProtocol.Pants.Type.LOGIN_REQUEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        loggedIn_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        versionMajor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        versionMinor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        versionPatch_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        channelId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        channelName_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.kndl.pants.PantsProtocol.internal_static_org_kndl_pants_Pants_descriptor;
      }

      public org.kndl.pants.PantsProtocol.Pants getDefaultInstanceForType() {
        return org.kndl.pants.PantsProtocol.Pants.getDefaultInstance();
      }

      public org.kndl.pants.PantsProtocol.Pants build() {
        org.kndl.pants.PantsProtocol.Pants result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.kndl.pants.PantsProtocol.Pants buildPartial() {
        org.kndl.pants.PantsProtocol.Pants result = new org.kndl.pants.PantsProtocol.Pants(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.loggedIn_ = loggedIn_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.versionMajor_ = versionMajor_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.versionMinor_ = versionMinor_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.versionPatch_ = versionPatch_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.channelId_ = channelId_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.channelName_ = channelName_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kndl.pants.PantsProtocol.Pants) {
          return mergeFrom((org.kndl.pants.PantsProtocol.Pants)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.kndl.pants.PantsProtocol.Pants other) {
        if (other == org.kndl.pants.PantsProtocol.Pants.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasUsername()) {
          bitField0_ |= 0x00000002;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000004;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasLoggedIn()) {
          setLoggedIn(other.getLoggedIn());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasVersionMajor()) {
          setVersionMajor(other.getVersionMajor());
        }
        if (other.hasVersionMinor()) {
          setVersionMinor(other.getVersionMinor());
        }
        if (other.hasVersionPatch()) {
          setVersionPatch(other.getVersionPatch());
        }
        if (other.hasChannelId()) {
          setChannelId(other.getChannelId());
        }
        if (other.hasChannelName()) {
          bitField0_ |= 0x00000200;
          channelName_ = other.channelName_;
          onChanged();
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000400;
          message_ = other.message_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.kndl.pants.PantsProtocol.Pants parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.kndl.pants.PantsProtocol.Pants) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.kndl.pants.PantsProtocol.Pants.Type type_ = org.kndl.pants.PantsProtocol.Pants.Type.LOGIN_REQUEST;
      /**
       * <code>required .org.kndl.pants.Pants.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .org.kndl.pants.Pants.Type type = 1;</code>
       */
      public org.kndl.pants.PantsProtocol.Pants.Type getType() {
        return type_;
      }
      /**
       * <code>required .org.kndl.pants.Pants.Type type = 1;</code>
       */
      public Builder setType(org.kndl.pants.PantsProtocol.Pants.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .org.kndl.pants.Pants.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.kndl.pants.PantsProtocol.Pants.Type.LOGIN_REQUEST;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 2;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000002);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 2;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 3;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000004);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }

      private boolean loggedIn_ ;
      /**
       * <code>optional bool loggedIn = 4;</code>
       */
      public boolean hasLoggedIn() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool loggedIn = 4;</code>
       */
      public boolean getLoggedIn() {
        return loggedIn_;
      }
      /**
       * <code>optional bool loggedIn = 4;</code>
       */
      public Builder setLoggedIn(boolean value) {
        bitField0_ |= 0x00000008;
        loggedIn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool loggedIn = 4;</code>
       */
      public Builder clearLoggedIn() {
        bitField0_ = (bitField0_ & ~0x00000008);
        loggedIn_ = false;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>optional int64 userId = 5;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 userId = 5;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>optional int64 userId = 5;</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000010;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 userId = 5;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private int versionMajor_ ;
      /**
       * <code>optional int32 versionMajor = 6;</code>
       */
      public boolean hasVersionMajor() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 versionMajor = 6;</code>
       */
      public int getVersionMajor() {
        return versionMajor_;
      }
      /**
       * <code>optional int32 versionMajor = 6;</code>
       */
      public Builder setVersionMajor(int value) {
        bitField0_ |= 0x00000020;
        versionMajor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 versionMajor = 6;</code>
       */
      public Builder clearVersionMajor() {
        bitField0_ = (bitField0_ & ~0x00000020);
        versionMajor_ = 0;
        onChanged();
        return this;
      }

      private int versionMinor_ ;
      /**
       * <code>optional int32 versionMinor = 7;</code>
       */
      public boolean hasVersionMinor() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 versionMinor = 7;</code>
       */
      public int getVersionMinor() {
        return versionMinor_;
      }
      /**
       * <code>optional int32 versionMinor = 7;</code>
       */
      public Builder setVersionMinor(int value) {
        bitField0_ |= 0x00000040;
        versionMinor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 versionMinor = 7;</code>
       */
      public Builder clearVersionMinor() {
        bitField0_ = (bitField0_ & ~0x00000040);
        versionMinor_ = 0;
        onChanged();
        return this;
      }

      private int versionPatch_ ;
      /**
       * <code>optional int32 versionPatch = 8;</code>
       */
      public boolean hasVersionPatch() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 versionPatch = 8;</code>
       */
      public int getVersionPatch() {
        return versionPatch_;
      }
      /**
       * <code>optional int32 versionPatch = 8;</code>
       */
      public Builder setVersionPatch(int value) {
        bitField0_ |= 0x00000080;
        versionPatch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 versionPatch = 8;</code>
       */
      public Builder clearVersionPatch() {
        bitField0_ = (bitField0_ & ~0x00000080);
        versionPatch_ = 0;
        onChanged();
        return this;
      }

      private long channelId_ ;
      /**
       * <code>optional int64 channelId = 9;</code>
       */
      public boolean hasChannelId() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int64 channelId = 9;</code>
       */
      public long getChannelId() {
        return channelId_;
      }
      /**
       * <code>optional int64 channelId = 9;</code>
       */
      public Builder setChannelId(long value) {
        bitField0_ |= 0x00000100;
        channelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 channelId = 9;</code>
       */
      public Builder clearChannelId() {
        bitField0_ = (bitField0_ & ~0x00000100);
        channelId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object channelName_ = "";
      /**
       * <code>optional string channelName = 10;</code>
       */
      public boolean hasChannelName() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string channelName = 10;</code>
       */
      public java.lang.String getChannelName() {
        java.lang.Object ref = channelName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            channelName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string channelName = 10;</code>
       */
      public com.google.protobuf.ByteString
          getChannelNameBytes() {
        java.lang.Object ref = channelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string channelName = 10;</code>
       */
      public Builder setChannelName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        channelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string channelName = 10;</code>
       */
      public Builder clearChannelName() {
        bitField0_ = (bitField0_ & ~0x00000200);
        channelName_ = getDefaultInstance().getChannelName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string channelName = 10;</code>
       */
      public Builder setChannelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        channelName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 11;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string message = 11;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 11;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 11;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 11;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000400);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 11;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        message_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 12;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int64 timestamp = 12;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 12;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000800;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 12;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000800);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 254;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional bytes data = 254;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 254;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 254;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00001000);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.kndl.pants.Pants)
    }

    static {
      defaultInstance = new Pants(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.kndl.pants.Pants)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_kndl_pants_Pants_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_kndl_pants_Pants_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%src/main/protobuf/PantsProtocol.proto\022" +
      "\016org.kndl.pants\"\256\003\n\005Pants\022(\n\004type\030\001 \002(\0162" +
      "\032.org.kndl.pants.Pants.Type\022\020\n\010username\030" +
      "\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\020\n\010loggedIn\030\004 \001(" +
      "\010\022\016\n\006userId\030\005 \001(\003\022\024\n\014versionMajor\030\006 \001(\005\022" +
      "\024\n\014versionMinor\030\007 \001(\005\022\024\n\014versionPatch\030\010 " +
      "\001(\005\022\021\n\tchannelId\030\t \001(\003\022\023\n\013channelName\030\n " +
      "\001(\t\022\017\n\007message\030\013 \001(\t\022\021\n\ttimestamp\030\014 \001(\003\022" +
      "\r\n\004data\030\376\001 \001(\014\"\227\001\n\004Type\022\021\n\rLOGIN_REQUEST" +
      "\020\000\022\022\n\016LOGIN_RESPONSE\020\001\022\013\n\007VERSION\020\002\022\020\n\014J",
      "OIN_REQUEST\020\003\022\021\n\rJOIN_RESPONSE\020\004\022\007\n\003MSG\020" +
      "\005\022\013\n\007PRIVMSG\020\006\022\010\n\004PING\020\007\022\010\n\004PONG\020\010\022\014\n\007CO" +
      "NTROL\020\376\001B\020\n\016org.kndl.pants"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_kndl_pants_Pants_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_kndl_pants_Pants_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_kndl_pants_Pants_descriptor,
        new java.lang.String[] { "Type", "Username", "Password", "LoggedIn", "UserId", "VersionMajor", "VersionMinor", "VersionPatch", "ChannelId", "ChannelName", "Message", "Timestamp", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
